project:
  type: book
  title: "Optimization basics"
  output-dir: public

cover: "BasicsOptim-Eq.png"
book:
  title: "Optimization"
  author: "Arno Veletanlic"
  subtitle: "Basics"
  archive: "optim.zip"
  sharing: twitter
  cover-image: static\Cover-Detail.png
  downloads: pdf
  site-url: "https://optim.arnov.dev"
  open-graph: true
  license: "CC BY-NC-SA 4.0"
  keyword: optimization, math, python, programming, data-science, machine-learning, multivariate-calculus, linear-algebra, statistics
  favicon: static\favicon.ico
  twitter-card:
    site: "https://optim.arnov.dev"
    creator: "@arno_shae"
    image: static\Book-Horizontal-adjusted.png
    title: "A small Optimization Book"
    description: "Optimization basics"
    card-style: summary_large_image
  page-navigation: true
  date: today
  navbar:
    show: true
    search: true
  chapters:
  - index.qmd
  - preface.qmd
  - part: "Basics"
    chapters: 
      - basics/first-definitions.qmd
      - basics/the-jacobian.qmd
  # - part: simple-optimization.qmd
  #   chapters:
  #     - line-search.qmd
  #     - linear-programming.qmd
  #     - quadratic-programming.qmd
  #     - nonlinear-programming.qmd
  # - part: advanced-optimization.qmd
  #   chapters:
  #     - the-lagrangian.qmd
  #     - the-lagrange-multiplier.qmd
  #     - the-kkt-conditions.qmd
  - part: "About"
    chapters:
      - about.qmd

  

bibliography: references.bib
link-citations: true
number-depth: 3

latex-auto-install: true
latex-auto-install-preamble: true
latex-auto-mk: true


parallax-background-size: cover
parallax-background-position: center
parallax-background-repeat: no-repeat
highlight-style: pygments


format:
  html:
      
    theme: quartz
    css:
      - ./theme/bootswatch/dist/quartz/bootstrap.css
      - ./theme/bootswatch/dist/quartz-custom/bootstrap.css
      - ./extras.css
      - ./theme.scss

    highlight-lines: true
    smooth-scroll: true
    html-math-method: katex
    katex: true
    katex-font: auto
    katex-unicode: true
    katex-unicode-font: auto
    fig-responsive: true

    fig-asp: 0.75
    fig-caption: true
    fig-caption-position: bottom
    fig-caption-justify: center
    fig-caption-spacing: 0.5em
    fig-caption-font-size: 0.8em
    footnotes-hover: true
    code-fold: true
    code-copy: true
    code-line-numbers: true
    code-tools: true
    code-tools-position: top
    include-in-header: 
      - katex.html
    include-after-body: 
      - license.html
      


